/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AccordionTab {
        "content": string;
        "title": string;
    }
    interface CallToAction {
        "buttonOne": string;
        "buttonTwo": string;
        "footerOneText": string;
        "footerTwoText": string;
        "headline": string;
        "imagePath": string;
        "mainText": string;
        "titleText": string;
    }
    interface ExampleComponent {
        "exampleProp": string;
    }
}
declare global {
    interface HTMLAccordionTabElement extends Components.AccordionTab, HTMLStencilElement {
    }
    var HTMLAccordionTabElement: {
        prototype: HTMLAccordionTabElement;
        new (): HTMLAccordionTabElement;
    };
    interface HTMLCallToActionElement extends Components.CallToAction, HTMLStencilElement {
    }
    var HTMLCallToActionElement: {
        prototype: HTMLCallToActionElement;
        new (): HTMLCallToActionElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "accordion-tab": HTMLAccordionTabElement;
        "call-to-action": HTMLCallToActionElement;
        "example-component": HTMLExampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface AccordionTab {
        "content"?: string;
        "title"?: string;
    }
    interface CallToAction {
        "buttonOne"?: string;
        "buttonTwo"?: string;
        "footerOneText"?: string;
        "footerTwoText"?: string;
        "headline"?: string;
        "imagePath"?: string;
        "mainText"?: string;
        "titleText"?: string;
    }
    interface ExampleComponent {
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "accordion-tab": AccordionTab;
        "call-to-action": CallToAction;
        "example-component": ExampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "accordion-tab": LocalJSX.AccordionTab & JSXBase.HTMLAttributes<HTMLAccordionTabElement>;
            "call-to-action": LocalJSX.CallToAction & JSXBase.HTMLAttributes<HTMLCallToActionElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
        }
    }
}
