/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CallToAction {
        "appearance": string;
        "buttonText": string;
        "footerText": string;
        "headline": string;
        "imagePath": string;
        "text": string;
        "titleText": string;
    }
    interface ExampleComponent {
        "exampleProp": string;
    }
}
declare global {
    interface HTMLCallToActionElement extends Components.CallToAction, HTMLStencilElement {
    }
    var HTMLCallToActionElement: {
        prototype: HTMLCallToActionElement;
        new (): HTMLCallToActionElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLElementTagNameMap {
        "call-to-action": HTMLCallToActionElement;
        "example-component": HTMLExampleComponentElement;
    }
}
declare namespace LocalJSX {
    interface CallToAction {
        "appearance"?: string;
        "buttonText"?: string;
        "footerText"?: string;
        "headline"?: string;
        "imagePath"?: string;
        "text"?: string;
        "titleText"?: string;
    }
    interface ExampleComponent {
        "exampleProp"?: string;
    }
    interface IntrinsicElements {
        "call-to-action": CallToAction;
        "example-component": ExampleComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "call-to-action": LocalJSX.CallToAction & JSXBase.HTMLAttributes<HTMLCallToActionElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
        }
    }
}
